@startuml
|NotificationPreferences|
|UserProfile|
|LoginView|
start
:Receive registration button click;
:readUsernameTextbox();
:readPasswordTextbox();
:readEmailTextbox();
:readNotificationPreferences();
:CreateNotificationPreferences object;
|NotificationPreferences|
:NotificationPreferences(frequency: NotificationFrequency, isEnabled: bool);
|LoginView|
:Create UserProfile object;
|UserProfile|
:UserProfile(username: string, email: string, notificationPreferences: NotificationPreferences);

|LoginView|

:registerUser(userProfile: UserProfile, password: string);

|AuthenticationManager|
:validateUsername(username: string);
if () then ([invalid username])
|LoginView|
    :displayError("Username must use only letters");
    stop
else ([valid username])
endif
|AuthenticationManager|

:validatePassword(password: string);
if () then ([invalid password])
|LoginView|
    :displayError("Password must be at least 8 characters long");
    stop
else ([valid password])
endif
|AuthenticationManager|

:hashPassword(password: string);
|AuthenticationManager|
:validateEmail(email: string);
if () then ([invalid email])
|LoginView|
    :displayError("Invalid email address");
    stop
else ([valid email])
endif
|AuthenticationManager|

:saveNewUser(userProfile: UserProfile, hashedPassword: string);

|UserStorageManager|
:findUserByUsername(username: string);
if () then ([user found])
|AuthenticationManager|
    :Return RegistrationStatus.USER_ALREADY_EXISTS;
|LoginView|
    :displayError("Username already exists");
    stop
else ([user not found])
|UserStorageManager|
:saveUserToDatabase(userProfile: UserProfile, hashedPassword: string);
|AuthenticationManager|
if () then ([save successful])
    |AuthenticationManager|
    :Return RegistrationStatus.SUCCESS;
|LoginView|
    :transitionToHomeView(userProfile: UserProfile);
    stop
else ([save unsuccessful])
    |AuthenticationManager|
    :\nReturn RegistrationStatus.UNKNOWN_ERROR\n;
|LoginView|
    :displayError("Registration failed. Internal error");
    stop
endif
@enduml
